// Data generated from dataset_alojamientos_transformacion_digital.xlsx
const BOOKINGS_DATA = [
  {
    "id_reserva": 1,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-12",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 129256,
    "ingreso_total_ars": 646280,
    "ocupacion_destino_pct": 63,
    "comision_booking_ars": 96942
  },
  {
    "id_reserva": 2,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-20",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 177397,
    "ingreso_total_ars": 532191,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 79828.65
  },
  {
    "id_reserva": 3,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-01",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 168907,
    "ingreso_total_ars": 1689070,
    "ocupacion_destino_pct": 41,
    "comision_booking_ars": 253360.5
  },
  {
    "id_reserva": 4,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-20",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 128893,
    "ingreso_total_ars": 1031144,
    "ocupacion_destino_pct": 83,
    "comision_booking_ars": 154671.6
  },
  {
    "id_reserva": 5,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-10",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 144597,
    "ingreso_total_ars": 1156776,
    "ocupacion_destino_pct": 72,
    "comision_booking_ars": 173516.4
  },
  {
    "id_reserva": 6,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-27",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 139797,
    "ingreso_total_ars": 419391,
    "ocupacion_destino_pct": 46,
    "comision_booking_ars": 62908.65
  },
  {
    "id_reserva": 7,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-09",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 235647,
    "ingreso_total_ars": 471294,
    "ocupacion_destino_pct": 89,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 8,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-21",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 138427,
    "ingreso_total_ars": 1384270,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 207640.5
  },
  {
    "id_reserva": 9,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-12",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 137930,
    "ingreso_total_ars": 689650,
    "ocupacion_destino_pct": 60,
    "comision_booking_ars": 103447.5
  },
  {
    "id_reserva": 10,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-13",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 173320,
    "ingreso_total_ars": 1559880,
    "ocupacion_destino_pct": 63,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 11,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-10",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 169840,
    "ingreso_total_ars": 509520,
    "ocupacion_destino_pct": 80,
    "comision_booking_ars": 76428
  },
  {
    "id_reserva": 12,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-11",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 139735,
    "ingreso_total_ars": 1257615,
    "ocupacion_destino_pct": 57,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 13,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-25",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 130021,
    "ingreso_total_ars": 260042,
    "ocupacion_destino_pct": 57,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 14,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-24",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 167869,
    "ingreso_total_ars": 1175083,
    "ocupacion_destino_pct": 95,
    "comision_booking_ars": 176262.45
  },
  {
    "id_reserva": 15,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-28",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 174718,
    "ingreso_total_ars": 698872,
    "ocupacion_destino_pct": 79,
    "comision_booking_ars": 104830.8
  },
  {
    "id_reserva": 16,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-09",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 166484,
    "ingreso_total_ars": 1331872,
    "ocupacion_destino_pct": 65,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 17,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-11",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 151915,
    "ingreso_total_ars": 1367235,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 205085.25
  },
  {
    "id_reserva": 18,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-19",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 140432,
    "ingreso_total_ars": 421296,
    "ocupacion_destino_pct": 64,
    "comision_booking_ars": 63194.4
  },
  {
    "id_reserva": 19,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-03-06",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 101504,
    "ingreso_total_ars": 1015040,
    "ocupacion_destino_pct": 62,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 20,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-29",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 138469,
    "ingreso_total_ars": 415407,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 21,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-09",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 113416,
    "ingreso_total_ars": 1134160,
    "ocupacion_destino_pct": 72,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 22,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-10",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 110032,
    "ingreso_total_ars": 550160,
    "ocupacion_destino_pct": 63,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 23,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-01",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 154042,
    "ingreso_total_ars": 1078294,
    "ocupacion_destino_pct": 41,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 24,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-03-03",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 121571,
    "ingreso_total_ars": 243142,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 25,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-18",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 106483,
    "ingreso_total_ars": 1064830,
    "ocupacion_destino_pct": 48,
    "comision_booking_ars": 159724.5
  },
  {
    "id_reserva": 26,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-12",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 169163,
    "ingreso_total_ars": 1014978,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 27,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-02-21",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 142296,
    "ingreso_total_ars": 853776,
    "ocupacion_destino_pct": 63,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 28,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-31",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 169451,
    "ingreso_total_ars": 847255,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 29,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-28",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 140942,
    "ingreso_total_ars": 704710,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 105706.5
  },
  {
    "id_reserva": 30,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-18",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 143309,
    "ingreso_total_ars": 286618,
    "ocupacion_destino_pct": 59,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 31,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-05",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 170678,
    "ingreso_total_ars": 853390,
    "ocupacion_destino_pct": 63,
    "comision_booking_ars": 128008.5
  },
  {
    "id_reserva": 32,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-05-28",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 131850,
    "ingreso_total_ars": 1186650,
    "ocupacion_destino_pct": 85,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 33,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-21",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 195519,
    "ingreso_total_ars": 1368633,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 205294.95
  },
  {
    "id_reserva": 34,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-26",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 192772,
    "ingreso_total_ars": 385544,
    "ocupacion_destino_pct": 98,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 35,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-05",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 164931,
    "ingreso_total_ars": 824655,
    "ocupacion_destino_pct": 92,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 36,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-13",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 172742,
    "ingreso_total_ars": 1554678,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 233201.7
  },
  {
    "id_reserva": 37,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-26",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 225477,
    "ingreso_total_ars": 450954,
    "ocupacion_destino_pct": 92,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 38,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-02-12",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 153653,
    "ingreso_total_ars": 1229224,
    "ocupacion_destino_pct": 70,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 39,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-02-12",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 90282,
    "ingreso_total_ars": 722256,
    "ocupacion_destino_pct": 64,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 40,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-03-15",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 231303,
    "ingreso_total_ars": 1850424,
    "ocupacion_destino_pct": 98,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 41,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-09",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 138890,
    "ingreso_total_ars": 694450,
    "ocupacion_destino_pct": 68,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 42,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-16",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 97492,
    "ingreso_total_ars": 682444,
    "ocupacion_destino_pct": 43,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 43,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-10",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 166562,
    "ingreso_total_ars": 333124,
    "ocupacion_destino_pct": 60,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 44,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-02",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 105713,
    "ingreso_total_ars": 845704,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 126855.6
  },
  {
    "id_reserva": 45,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-21",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 176163,
    "ingreso_total_ars": 1409304,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 46,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-22",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 131285,
    "ingreso_total_ars": 918995,
    "ocupacion_destino_pct": 71,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 47,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-18",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 181441,
    "ingreso_total_ars": 1632969,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 244945.35
  },
  {
    "id_reserva": 48,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-26",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 160468,
    "ingreso_total_ars": 481404,
    "ocupacion_destino_pct": 53,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 49,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-18",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 148434,
    "ingreso_total_ars": 742170,
    "ocupacion_destino_pct": 73,
    "comision_booking_ars": 111325.5
  },
  {
    "id_reserva": 50,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-19",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 91025,
    "ingreso_total_ars": 910250,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 136537.5
  },
  {
    "id_reserva": 51,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-02-04",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 155129,
    "ingreso_total_ars": 930774,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 52,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-14",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 194058,
    "ingreso_total_ars": 970290,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 53,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-05-10",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 122914,
    "ingreso_total_ars": 1106226,
    "ocupacion_destino_pct": 43,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 54,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-12",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 133719,
    "ingreso_total_ars": 267438,
    "ocupacion_destino_pct": 48,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 55,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-04-24",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 192493,
    "ingreso_total_ars": 1924930,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 56,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-08",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 104722,
    "ingreso_total_ars": 1047220,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 157083
  },
  {
    "id_reserva": 57,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-02",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 140404,
    "ingreso_total_ars": 280808,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 58,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-05",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 136357,
    "ingreso_total_ars": 409071,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 59,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-02-09",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 253325,
    "ingreso_total_ars": 1266625,
    "ocupacion_destino_pct": 80,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 60,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-02-15",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 143964,
    "ingreso_total_ars": 1007748,
    "ocupacion_destino_pct": 55,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 61,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-28",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 254316,
    "ingreso_total_ars": 2034528,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 305179.2
  },
  {
    "id_reserva": 62,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-31",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 247549,
    "ingreso_total_ars": 1485294,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 222794.1
  },
  {
    "id_reserva": 63,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-13",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 126517,
    "ingreso_total_ars": 885619,
    "ocupacion_destino_pct": 44,
    "comision_booking_ars": 132842.85
  },
  {
    "id_reserva": 64,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-13",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 183404,
    "ingreso_total_ars": 1834040,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 275106
  },
  {
    "id_reserva": 65,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-02-15",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 95014,
    "ingreso_total_ars": 570084,
    "ocupacion_destino_pct": 46,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 66,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-22",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 179457,
    "ingreso_total_ars": 1435656,
    "ocupacion_destino_pct": 87,
    "comision_booking_ars": 215348.4
  },
  {
    "id_reserva": 67,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-18",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 95817,
    "ingreso_total_ars": 574902,
    "ocupacion_destino_pct": 67,
    "comision_booking_ars": 86235.3
  },
  {
    "id_reserva": 68,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-20",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 146531,
    "ingreso_total_ars": 1025717,
    "ocupacion_destino_pct": 44,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 69,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-03-22",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 194339,
    "ingreso_total_ars": 583017,
    "ocupacion_destino_pct": 74,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 70,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-25",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 191384,
    "ingreso_total_ars": 1531072,
    "ocupacion_destino_pct": 73,
    "comision_booking_ars": 229660.8
  },
  {
    "id_reserva": 71,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-08",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 180676,
    "ingreso_total_ars": 722704,
    "ocupacion_destino_pct": 74,
    "comision_booking_ars": 108405.6
  },
  {
    "id_reserva": 72,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-19",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 167549,
    "ingreso_total_ars": 1005294,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 73,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-04-30",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 157954,
    "ingreso_total_ars": 1421586,
    "ocupacion_destino_pct": 68,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 74,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-13",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 137196,
    "ingreso_total_ars": 411588,
    "ocupacion_destino_pct": 87,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 75,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-24",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 188184,
    "ingreso_total_ars": 940920,
    "ocupacion_destino_pct": 74,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 76,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-07",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 122092,
    "ingreso_total_ars": 244184,
    "ocupacion_destino_pct": 70,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 77,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-04-27",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 182544,
    "ingreso_total_ars": 1460352,
    "ocupacion_destino_pct": 67,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 78,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-04-13",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 119342,
    "ingreso_total_ars": 596710,
    "ocupacion_destino_pct": 55,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 79,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-02-15",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 150889,
    "ingreso_total_ars": 1508890,
    "ocupacion_destino_pct": 43,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 80,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-27",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 160901,
    "ingreso_total_ars": 643604,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 96540.6
  },
  {
    "id_reserva": 81,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-05-10",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 171810,
    "ingreso_total_ars": 1374480,
    "ocupacion_destino_pct": 83,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 82,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-04-26",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 122406,
    "ingreso_total_ars": 734436,
    "ocupacion_destino_pct": 80,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 83,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-05",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 175992,
    "ingreso_total_ars": 879960,
    "ocupacion_destino_pct": 89,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 84,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-11",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 131904,
    "ingreso_total_ars": 923328,
    "ocupacion_destino_pct": 74,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 85,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-09",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 118043,
    "ingreso_total_ars": 472172,
    "ocupacion_destino_pct": 44,
    "comision_booking_ars": 70825.8
  },
  {
    "id_reserva": 86,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-30",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 148161,
    "ingreso_total_ars": 1185288,
    "ocupacion_destino_pct": 81,
    "comision_booking_ars": 177793.2
  },
  {
    "id_reserva": 87,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-06",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 202518,
    "ingreso_total_ars": 1620144,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 243021.6
  },
  {
    "id_reserva": 88,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-18",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 237978,
    "ingreso_total_ars": 2379780,
    "ocupacion_destino_pct": 98,
    "comision_booking_ars": 356967
  },
  {
    "id_reserva": 89,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-05",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 135774,
    "ingreso_total_ars": 678870,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 90,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-14",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 250166,
    "ingreso_total_ars": 1000664,
    "ocupacion_destino_pct": 89,
    "comision_booking_ars": 150099.6
  },
  {
    "id_reserva": 91,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-07",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 167580,
    "ingreso_total_ars": 1340640,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 92,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-20",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 160515,
    "ingreso_total_ars": 642060,
    "ocupacion_destino_pct": 66,
    "comision_booking_ars": 96309
  },
  {
    "id_reserva": 93,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-24",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 132840,
    "ingreso_total_ars": 1195560,
    "ocupacion_destino_pct": 61,
    "comision_booking_ars": 179334
  },
  {
    "id_reserva": 94,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-06",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 201644,
    "ingreso_total_ars": 604932,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 90739.8
  },
  {
    "id_reserva": 95,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-27",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 185426,
    "ingreso_total_ars": 556278,
    "ocupacion_destino_pct": 57,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 96,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-06",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 121266,
    "ingreso_total_ars": 485064,
    "ocupacion_destino_pct": 48,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 97,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-25",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 231680,
    "ingreso_total_ars": 2085120,
    "ocupacion_destino_pct": 83,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 98,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-30",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 180768,
    "ingreso_total_ars": 723072,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 108460.8
  },
  {
    "id_reserva": 99,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-28",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 151990,
    "ingreso_total_ars": 1215920,
    "ocupacion_destino_pct": 67,
    "comision_booking_ars": 182388
  },
  {
    "id_reserva": 100,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-04",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 129529,
    "ingreso_total_ars": 388587,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 101,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-11",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 159827,
    "ingreso_total_ars": 1118789,
    "ocupacion_destino_pct": 67,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 102,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-29",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 155057,
    "ingreso_total_ars": 310114,
    "ocupacion_destino_pct": 86,
    "comision_booking_ars": 46517.1
  },
  {
    "id_reserva": 103,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-28",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 147080,
    "ingreso_total_ars": 588320,
    "ocupacion_destino_pct": 51,
    "comision_booking_ars": 88248
  },
  {
    "id_reserva": 104,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-11",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 163372,
    "ingreso_total_ars": 1633720,
    "ocupacion_destino_pct": 84,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 105,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-10",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 251635,
    "ingreso_total_ars": 1761445,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 106,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-04",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 164691,
    "ingreso_total_ars": 1482219,
    "ocupacion_destino_pct": 79,
    "comision_booking_ars": 222332.85
  },
  {
    "id_reserva": 107,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-07",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 123834,
    "ingreso_total_ars": 866838,
    "ocupacion_destino_pct": 86,
    "comision_booking_ars": 130025.7
  },
  {
    "id_reserva": 108,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-29",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 168139,
    "ingreso_total_ars": 1008834,
    "ocupacion_destino_pct": 57,
    "comision_booking_ars": 151325.1
  },
  {
    "id_reserva": 109,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-22",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 194381,
    "ingreso_total_ars": 971905,
    "ocupacion_destino_pct": 81,
    "comision_booking_ars": 145785.75
  },
  {
    "id_reserva": 110,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-05-02",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 198743,
    "ingreso_total_ars": 1788687,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 111,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-04",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 177026,
    "ingreso_total_ars": 1062156,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 159323.4
  },
  {
    "id_reserva": 112,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-30",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 237771,
    "ingreso_total_ars": 1902168,
    "ocupacion_destino_pct": 92,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 113,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-11",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 172951,
    "ingreso_total_ars": 1037706,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 155655.9
  },
  {
    "id_reserva": 114,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-31",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 114267,
    "ingreso_total_ars": 1142670,
    "ocupacion_destino_pct": 52,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 115,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-31",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 168222,
    "ingreso_total_ars": 1682220,
    "ocupacion_destino_pct": 58,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 116,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-02-28",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 113519,
    "ingreso_total_ars": 794633,
    "ocupacion_destino_pct": 59,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 117,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-12",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 97146,
    "ingreso_total_ars": 194292,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 118,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-05-06",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 254389,
    "ingreso_total_ars": 763167,
    "ocupacion_destino_pct": 75,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 119,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-23",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 124164,
    "ingreso_total_ars": 869148,
    "ocupacion_destino_pct": 58,
    "comision_booking_ars": 130372.2
  },
  {
    "id_reserva": 120,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-30",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 192521,
    "ingreso_total_ars": 577563,
    "ocupacion_destino_pct": 90,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 121,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-14",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 109555,
    "ingreso_total_ars": 438220,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 122,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-31",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 240197,
    "ingreso_total_ars": 2401970,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 360295.5
  },
  {
    "id_reserva": 123,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-27",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 149856,
    "ingreso_total_ars": 1498560,
    "ocupacion_destino_pct": 83,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 124,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-20",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 214531,
    "ingreso_total_ars": 1287186,
    "ocupacion_destino_pct": 94,
    "comision_booking_ars": 193077.9
  },
  {
    "id_reserva": 125,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-01-26",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 171987,
    "ingreso_total_ars": 859935,
    "ocupacion_destino_pct": 53,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 126,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-03",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 212350,
    "ingreso_total_ars": 849400,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 127,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-01",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 94278,
    "ingreso_total_ars": 565668,
    "ocupacion_destino_pct": 54,
    "comision_booking_ars": 84850.2
  },
  {
    "id_reserva": 128,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-04-27",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 230096,
    "ingreso_total_ars": 690288,
    "ocupacion_destino_pct": 82,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 129,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-31",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 195723,
    "ingreso_total_ars": 978615,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 130,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-10",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 109359,
    "ingreso_total_ars": 437436,
    "ocupacion_destino_pct": 58,
    "comision_booking_ars": 65615.4
  },
  {
    "id_reserva": 131,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-26",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 147560,
    "ingreso_total_ars": 885360,
    "ocupacion_destino_pct": 47,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 132,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-04-14",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 205597,
    "ingreso_total_ars": 1233582,
    "ocupacion_destino_pct": 92,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 133,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-11",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 236276,
    "ingreso_total_ars": 1890208,
    "ocupacion_destino_pct": 85,
    "comision_booking_ars": 283531.2
  },
  {
    "id_reserva": 134,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-28",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 188117,
    "ingreso_total_ars": 376234,
    "ocupacion_destino_pct": 72,
    "comision_booking_ars": 56435.1
  },
  {
    "id_reserva": 135,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-01",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 185394,
    "ingreso_total_ars": 1853940,
    "ocupacion_destino_pct": 83,
    "comision_booking_ars": 278091
  },
  {
    "id_reserva": 136,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-22",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 151959,
    "ingreso_total_ars": 1367631,
    "ocupacion_destino_pct": 90,
    "comision_booking_ars": 205144.65
  },
  {
    "id_reserva": 137,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-27",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 183228,
    "ingreso_total_ars": 732912,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 109936.8
  },
  {
    "id_reserva": 138,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-04-13",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 104809,
    "ingreso_total_ars": 1048090,
    "ocupacion_destino_pct": 84,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 139,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-30",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 157449,
    "ingreso_total_ars": 1259592,
    "ocupacion_destino_pct": 40,
    "comision_booking_ars": 188938.8
  },
  {
    "id_reserva": 140,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-04-16",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 124586,
    "ingreso_total_ars": 249172,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 141,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-04-24",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 166680,
    "ingreso_total_ars": 333360,
    "ocupacion_destino_pct": 83,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 142,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-23",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 115915,
    "ingreso_total_ars": 1043235,
    "ocupacion_destino_pct": 56,
    "comision_booking_ars": 156485.25
  },
  {
    "id_reserva": 143,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-10",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 172199,
    "ingreso_total_ars": 1033194,
    "ocupacion_destino_pct": 55,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 144,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-30",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 115396,
    "ingreso_total_ars": 1038564,
    "ocupacion_destino_pct": 64,
    "comision_booking_ars": 155784.6
  },
  {
    "id_reserva": 145,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-05-11",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 194459,
    "ingreso_total_ars": 1166754,
    "ocupacion_destino_pct": 90,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 146,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-02-07",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 164983,
    "ingreso_total_ars": 1319864,
    "ocupacion_destino_pct": 94,
    "comision_booking_ars": 197979.6
  },
  {
    "id_reserva": 147,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-18",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 154387,
    "ingreso_total_ars": 926322,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 148,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-14",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 176931,
    "ingreso_total_ars": 1061586,
    "ocupacion_destino_pct": 86,
    "comision_booking_ars": 159237.9
  },
  {
    "id_reserva": 149,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-30",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 162340,
    "ingreso_total_ars": 1136380,
    "ocupacion_destino_pct": 74,
    "comision_booking_ars": 170457
  },
  {
    "id_reserva": 150,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-18",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 214946,
    "ingreso_total_ars": 1074730,
    "ocupacion_destino_pct": 87,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 151,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-01-12",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 151993,
    "ingreso_total_ars": 1063951,
    "ocupacion_destino_pct": 64,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 152,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-02-08",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 144852,
    "ingreso_total_ars": 1303668,
    "ocupacion_destino_pct": 79,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 153,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-26",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 113069,
    "ingreso_total_ars": 1017621,
    "ocupacion_destino_pct": 88,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 154,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-15",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 149807,
    "ingreso_total_ars": 599228,
    "ocupacion_destino_pct": 90,
    "comision_booking_ars": 89884.2
  },
  {
    "id_reserva": 155,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-12",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 251642,
    "ingreso_total_ars": 754926,
    "ocupacion_destino_pct": 85,
    "comision_booking_ars": 113238.9
  },
  {
    "id_reserva": 156,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-03-23",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 170912,
    "ingreso_total_ars": 1538208,
    "ocupacion_destino_pct": 57,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 157,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-15",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 197880,
    "ingreso_total_ars": 989400,
    "ocupacion_destino_pct": 60,
    "comision_booking_ars": 148410
  },
  {
    "id_reserva": 158,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-26",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 161805,
    "ingreso_total_ars": 1456245,
    "ocupacion_destino_pct": 97,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 159,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-03-25",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 178452,
    "ingreso_total_ars": 356904,
    "ocupacion_destino_pct": 86,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 160,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-16",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 214177,
    "ingreso_total_ars": 1713416,
    "ocupacion_destino_pct": 96,
    "comision_booking_ars": 257012.4
  },
  {
    "id_reserva": 161,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-04-08",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 155230,
    "ingreso_total_ars": 776150,
    "ocupacion_destino_pct": 77,
    "comision_booking_ars": 116422.5
  },
  {
    "id_reserva": 162,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-07",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 123466,
    "ingreso_total_ars": 1111194,
    "ocupacion_destino_pct": 40,
    "comision_booking_ars": 166679.1
  },
  {
    "id_reserva": 163,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-05-20",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 149681,
    "ingreso_total_ars": 598724,
    "ocupacion_destino_pct": 89,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 164,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-04-19",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 199878,
    "ingreso_total_ars": 1199268,
    "ocupacion_destino_pct": 84,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 165,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-28",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 139986,
    "ingreso_total_ars": 699930,
    "ocupacion_destino_pct": 76,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 166,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-03-17",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 248794,
    "ingreso_total_ars": 497588,
    "ocupacion_destino_pct": 96,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 167,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-13",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 249161,
    "ingreso_total_ars": 2242449,
    "ocupacion_destino_pct": 84,
    "comision_booking_ars": 336367.35
  },
  {
    "id_reserva": 168,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-26",
    "cantidad_noches": 5,
    "tarifa_noche_ars": 171381,
    "ingreso_total_ars": 856905,
    "ocupacion_destino_pct": 56,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 169,
    "destino": "Córdoba",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-02-05",
    "cantidad_noches": 3,
    "tarifa_noche_ars": 182242,
    "ingreso_total_ars": 546726,
    "ocupacion_destino_pct": 57,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 170,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-29",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 235991,
    "ingreso_total_ars": 1651937,
    "ocupacion_destino_pct": 79,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 171,
    "destino": "Monte Hermoso",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-04-17",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 116318,
    "ingreso_total_ars": 465272,
    "ocupacion_destino_pct": 48,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 172,
    "destino": "Córdoba",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "WhatsApp",
    "fecha_reserva": "2026-05-16",
    "cantidad_noches": 10,
    "tarifa_noche_ars": 135720,
    "ingreso_total_ars": 1357200,
    "ocupacion_destino_pct": 65,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 173,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-03-17",
    "cantidad_noches": 7,
    "tarifa_noche_ars": 245412,
    "ingreso_total_ars": 1717884,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 174,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-02-27",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 250853,
    "ingreso_total_ars": 2006824,
    "ocupacion_destino_pct": 92,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 175,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Familiar",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-01-04",
    "cantidad_noches": 6,
    "tarifa_noche_ars": 210329,
    "ingreso_total_ars": 1261974,
    "ocupacion_destino_pct": 78,
    "comision_booking_ars": 189296.1
  },
  {
    "id_reserva": 176,
    "destino": "Bariloche",
    "tipo_alojamiento": "Suite Premium",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-03-09",
    "cantidad_noches": 8,
    "tarifa_noche_ars": 247795,
    "ingreso_total_ars": 1982360,
    "ocupacion_destino_pct": 95,
    "comision_booking_ars": 297354
  },
  {
    "id_reserva": 177,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-01",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 221205,
    "ingreso_total_ars": 442410,
    "ocupacion_destino_pct": 92,
    "comision_booking_ars": 66361.5
  },
  {
    "id_reserva": 178,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Instagram",
    "fecha_reserva": "2026-01-17",
    "cantidad_noches": 9,
    "tarifa_noche_ars": 259195,
    "ingreso_total_ars": 2332755,
    "ocupacion_destino_pct": 97,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 179,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Web Propia",
    "fecha_reserva": "2026-02-05",
    "cantidad_noches": 2,
    "tarifa_noche_ars": 144877,
    "ingreso_total_ars": 289754,
    "ocupacion_destino_pct": 84,
    "comision_booking_ars": 0
  },
  {
    "id_reserva": 180,
    "destino": "Bariloche",
    "tipo_alojamiento": "Cabaña Standard",
    "canal_reserva": "Booking",
    "fecha_reserva": "2026-05-18",
    "cantidad_noches": 4,
    "tarifa_noche_ars": 190940,
    "ingreso_total_ars": 763760,
    "ocupacion_destino_pct": 89,
    "comision_booking_ars": 114564
  }
];
